version: '3.8'
services:
 
  nginx:
    build:
      context: ./nginx
    image: nginx:v0.1
    container_name: nginx
    ports:
    - "80:80"
    depends_on:
    - django
 
  django:
    build:
      context: ./django
    image: django:v0.1 
    ports:
    - "3000:3000"
    environment:
      MYSQL_USER: sampleblog
      MYSQL_PASSWORD: sampleblog
      MYSQL_DATABASE: sampleblog 
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      REDIS_HOST: redis
    container_name: django
    depends_on:
    - mysql
 
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER: sampleblog
      MYSQL_PASSWORD: sampleblog
      MYSQL_ROOT_PASSWORD: sampleblog
      MYSQL_DATABASE: sampleblog
    container_name: mysql
    ports:
    - "3306:3306"
  
  redis:
    image: redis:7.0
    ports:
    - "6379:6379"
