apiVersion: v1
kind: Secret
metadata:
  name: django-mysql-pass
  labels:
    app: sample-blog
    tier: django
data:
  MYSQL_PASSWORD: c2FtcGxlYmxvZw==
  MYSQL_ROOT_PASSWORD: c2FtcGxlYmxvZw==
  BLOG_ADMIN_PASSWORD: YWRtaW4= 
